import { DeliveryOption, PaymentOption, CheckoutStep } from "../types/checkout.types";
import { Package, Truck, CreditCard, Check } from "lucide-react";

// Delivery Options
export const DELIVERY_OPTIONS: DeliveryOption[] = [
  {
    id: "standard",
    name: "Standard Shipping",
    description: "Delivery in 5-7 business days",
    price: 4.99,
    estimatedDays: "5-7 business days",
  },
  {
    id: "express",
    name: "Express Shipping",
    description: "Delivery in 2-3 business days",
    price: 9.99,
    estimatedDays: "2-3 business days",
  },
  {
    id: "next-day",
    name: "Next Day Delivery",
    description: "Order before 2pm for next day delivery",
    price: 19.99,
    estimatedDays: "Next day",
  },
];

// Payment Options
export const PAYMENT_OPTIONS: PaymentOption[] = [
  {
    id: "credit-card",
    name: "Credit / Debit Card",
    description: "Pay securely with your card",
    icon: "credit-card",
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Pay with your PayPal account",
    icon: "paypal",
  },
];

// Checkout Steps
export const CHECKOUT_STEPS: CheckoutStep[] = [
  {
    id: 1,
    title: "Shipping",
    description: "Enter shipping information",
    icon: "package",
    isCompleted: false,
    isActive: true,
  },
  {
    id: 2,
    title: "Delivery",
    description: "Choose delivery method",
    icon: "truck",
    isCompleted: false,
    isActive: false,
  },
  {
    id: 3,
    title: "Payment",
    description: "Complete payment",
    icon: "credit-card",
    isCompleted: false,
    isActive: false,
  },
  {
    id: 4,
    title: "Review",
    description: "Review your order",
    icon: "check",
    isCompleted: false,
    isActive: false,
  },
];

// Tax Rate
export const TAX_RATE = 0.07; // 7%

// Countries List
export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Slovakia",
  "Slovenia",
  "Croatia",
  "Serbia",
  "Bulgaria",
  "Romania",
  "Greece",
  "Portugal",
  "Ireland",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Iceland",
  "Liechtenstein",
  "Monaco",
  "San Marino",
  "Vatican City",
  "Andorra",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "China",
  "India",
  "Brazil",
  "Argentina",
  "Chile",
  "Mexico",
  "South Africa",
  "Egypt",
  "Morocco",
  "Tunisia",
  "Algeria",
  "Libya",
  "Sudan",
  "Ethiopia",
  "Kenya",
  "Uganda",
  "Tanzania",
  "Nigeria",
  "Ghana",
  "Senegal",
  "Mali",
  "Burkina Faso",
  "Niger",
  "Chad",
  "Cameroon",
  "Central African Republic",
  "Gabon",
  "Congo",
  "Democratic Republic of the Congo",
  "Angola",
  "Zambia",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Lesotho",
  "Eswatini",
  "Mozambique",
  "Madagascar",
  "Mauritius",
  "Seychelles",
  "Comoros",
  "Djibouti",
  "Somalia",
  "Eritrea",
  "Burundi",
  "Rwanda",
  "Congo",
  "Equatorial Guinea",
  "Sao Tome and Principe",
  "Cape Verde",
  "Guinea-Bissau",
  "Guinea",
  "Sierra Leone",
  "Liberia",
  "Ivory Coast",
  "Togo",
  "Benin",
  "Equatorial Guinea",
  "Sao Tome and Principe",
  "Cape Verde",
  "Guinea-Bissau",
  "Guinea",
  "Sierra Leone",
  "Liberia",
  "Ivory Coast",
  "Togo",
  "Benin",
];
